In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import model_selection

In [69]:
def create_folds(data):
    data['kfold'] = -1
    
    data = data.sample(frac=1).reset_index(drop=True)
    
    num_bins = np.floor(1 + np.log2(len(data)))
    
    data.loc[:, 'bins'] = pd.cut(
        data['target'], bins = int(num_bins), labels = False
    )
    kf = model_selection.StratifiedKFold(n_splits = 5)
    for f, (t_, v_) in enumerate(kf.split(X=data, y = data.bins.values)):
        print(f), print(' ')
        print(t_), print(' ')
        print(v_), print(' ')
        data.loc[v_, 'kfold'] = f
    
    data = data.drop('bins', axis = 1)
    
    return data

In [70]:
X, y = datasets.make_regression( n_samples = 15000, n_features = 100, n_targets = 1)
df = pd.DataFrame(X, columns = [f'f_{i}' for i in range(X.shape[1])])
df.loc[:, 'target'] = y

In [71]:
df.head()

f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0 -1.484328  1.182369 -0.574792 -0.615991  0.514050  0.114719 -0.124999   
1  0.193110  0.167554  1.232662  0.118989  0.413704 -1.188519 -0.015786   
2  0.655615 -0.458892 -0.690228  0.532104  0.111328 -0.671696 -1.452936   
3  2.857441  1.306130 -0.867378  0.117355 -0.511969  0.364917  0.657136   
4 -1.869826  0.005379  1.331509 -1.147966  0.967723 -1.176837 -0.052228   

        f_7       f_8       f_9  ...      f_91      f_92      f_93      f_94  \
0 -0.213301  0.178923 -1.044408  ... -0.469886 -0.375407  1.193080  3.014717   
1 -1.751908 -1.272523 -0.154628  ... -0.006736 -0.723223  1.152635  1.449803   
2  1.203722  0.447595  0.208076  ...  2.197944  0.749309  0.498138  0.155201   
3 -2.088921 -0.545970  1.946379  ... -0.706310 -3.060594  0.228974 -2.018923   
4  0.128610 -0.365320 -0.653881  ...  0.148805 -0.325057  0.686479  2.318396   

       f_95      f_96      f_97      f_98      f_99      target  
0  0.284560 -0.073605 -0.912613  0.948379 -1.036810    3.024093  
1 -0.426057 -1.859479  1.558751 -1.940464  0.198883  -30.831905  
2 -1.589911  0.114090  0.579026 -0.673490  0.378613  -37.021120  
3  1.277559 -0.985244 -0.814621  1.118917 -0.777233  243.374892  
4 -0.610475 -0.333273 -1.975015 -0.411520  2.562030 -158.964849  

[5 rows x 101 columns]

In [78]:
df_1 = create_folds(df)

0
 
[ 2372  2830  2833 ... 14997 14998 14999]
 
[   0    1    2 ... 3222 3275 3394]
 
1
 
[    0     1     2 ... 14997 14998 14999]
 
[2372 2830 2833 ... 6504 6519 6842]
 
2
 
[    0     1     2 ... 14997 14998 14999]
 
[ 4366  5541  5574 ... 10246 10255 10439]
 
3
 
[    0     1     2 ... 14997 14998 14999]
 
[ 5974  8632  8786 ... 12400 12424 12569]
 
4
 
[    0     1     2 ... 12400 12424 12569]
 
[ 6467  9904 11703 ... 14997 14998 14999]
 


In [79]:
df_1.tail(30)

f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
14970 -0.073409  1.935839  2.815946 -0.040539 -0.177488  0.354470 -0.405054   
14971 -0.183316  0.085383  0.467468 -1.255173 -0.167519  0.404414  1.975946   
14972 -0.837978  0.065367  0.578595  1.084332  0.202756  0.213729 -0.325475   
14973 -1.438704  1.120182  0.524370 -0.940348  1.693549  0.632267  0.015285   
14974 -1.825863 -0.295549 -0.602726 -1.139397  0.282674  0.336064  0.582661   
14975 -0.285147  0.617213  0.956291  0.276001 -0.154190 -0.452725  0.452454   
14976  0.771930 -0.669553  1.594640  0.272783  3.171255  1.279284 -0.064103   
14977 -0.076034 -0.894372 -0.492656 -0.045238  0.589584  0.084541 -0.442672   
14978 -1.788061  0.454306  0.595587  0.330840  0.143994 -2.313516 -0.452894   
14979  0.432027 -0.543121  0.016403 -0.328724 -0.701942 -1.255637  1.184327   
14980 -0.461244  1.587330 -0.466098 -1.900136  0.040867 -1.250103 -1.155819   
14981 -0.682262 -0.085464  1.746830  0.502561  0.199420 -0.682924 -1.807544   
14982  1.614187 -1.048707 -0.364188  1.217784 -0.132574 -0.109771  0.176849   
14983 -0.209875 -1.444117 -0.586939 -1.415845  0.065458  0.436631 -0.831069   
14984  0.017640 -1.644426 -0.747888  2.219533 -0.368311  0.072773 -0.952500   
14985 -1.361127 -1.681612 -0.793787  1.660681  0.939226  1.769658 -0.636244   
14986 -0.285537 -1.367203 -0.155698 -0.146211 -0.253444  0.178388  0.418331   
14987  0.504193  0.478348 -1.532534  1.367596  0.318054  0.606066 -0.342659   
14988  1.321235  1.009107 -0.585076  1.531542 -0.329881 -0.110942  0.743987   
14989  0.757116 -0.783395 -0.098908 -1.260435  0.581831 -1.128951  0.225497   
14990  0.617206  0.359295 -0.234103  0.184782  0.290682 -1.121089 -0.414522   
14991  0.375023 -0.458842 -0.254138 -1.106519  0.712428 -1.733705  0.804066   
14992  0.320913  0.172498 -1.679714  0.844192 -1.556203  0.583119 -1.246556   
14993 -1.544685  0.492968 -0.393780  0.297298  0.240439 -0.834518 -0.515208   
14994  1.122454  0.288913  0.245434  0.895602  0.384142  0.111862  0.587832   
14995  1.144499  0.219859 -0.777710 -0.370905 -0.047794 -1.505450  0.756462   
14996  0.461560 -0.032690  0.920337  2.264532  1.376672  1.864768  0.348098   
14997 -0.119670 -0.695816  0.188332 -0.760183 -0.513276 -0.017745  0.629666   
14998  0.030346  0.862222  0.522984 -0.008885 -0.159495  0.284324  1.831877   
14999  0.795776 -0.555459  0.058857 -1.150309 -1.574394 -0.349154 -0.872121   

            f_7       f_8       f_9  ...      f_92      f_93      f_94  \
14970  0.721314 -1.576358 -0.578664  ...  1.621799 -0.324799 -0.385271   
14971  0.671486  0.405693  2.004559  ...  1.960390  0.618714 -1.383530   
14972  1.281426 -0.645752  0.107934  ...  0.385044  1.117194 -0.053291   
14973 -1.102906  0.864716 -0.777419  ...  1.179465  0.640164 -0.396530   
14974 -0.059644  0.093835  1.919468  ...  0.524582 -1.528883 -0.349817   
14975 -1.572187 -1.408494  0.243112  ...  0.534993 -0.186079  1.659598   
14976 -1.138377 -0.478886 -0.839825  ...  0.664863  0.177619  0.172181   
14977 -0.346102 -0.675127 -2.030113  ...  0.771830  0.239702 -0.410019   
14978 -0.415574 -0.442174  0.302479  ... -1.260758  1.541950 -0.550306   
14979 -1.916637 -0.485380  0.553426  ...  0.738095  0.167206  0.858090   
14980  0.221830  0.385465  0.978631  ... -1.105512 -0.357108  0.447178   
14981  0.819893  2.146332 -0.551105  ... -0.167048 -0.815764 -0.389688   
14982 -0.726165 -0.557783 -0.560216  ...  0.434036 -1.250501  0.582310   
14983 -0.577031 -0.250391 -1.584367  ...  0.558116 -0.488139 -1.450449   
14984 -0.743600 -1.133497 -0.440705  ... -0.919216  1.305455 -1.722930   
14985 -0.130161 -1.205017  0.342394  ...  2.052235 -1.289459  0.594708   
14986  0.951139  0.092523 -1.541207  ... -0.036576  2.249911  1.274766   
14987 -1.705727  0.871298 -0.629181  ... -0.671161 -0.697485 -0.193919   
14988  0.182384  2.491870 -1.784962  ... -0.995075 -1.184166  1.112699   
14989  2.419552 -1.182795  1.166239  ... -0.334374 -0.875923  0.622013   
14990 -0

In [80]:
df_1 = df_1.sample(frac=1).reset_index()

In [81]:
df_1.head()

index       f_0       f_1       f_2       f_3       f_4       f_5  \
0   5736 -0.949732  2.648627 -0.956029 -0.659839  0.001028  0.368446   
1   3897 -0.666421 -1.634138  0.711889 -0.361687  1.265688 -0.001180   
2  12385  0.422896  2.775942  1.395760  0.006723  0.095657  3.444344   
3  10553 -0.450566 -0.752190 -0.311539  0.484030  0.383313 -1.695040   
4   3731 -2.210837 -0.260171 -0.135624 -1.222982 -0.284386 -0.096053   

        f_6       f_7       f_8  ...      f_92      f_93      f_94      f_95  \
0 -0.649001  1.010351 -0.266103  ... -0.164147 -1.806141  1.664402 -0.803973   
1  0.933482 -1.039037  0.047661  ...  1.275942 -0.635454 -0.612535 -0.190689   
2 -1.237212 -0.477181  0.658501  ... -1.195856 -1.664252  2.699797  1.095726   
3 -0.407795  0.564327 -0.652386  ... -0.862184  2.477488  1.673945 -0.054777   
4  1.086329 -0.052931 -0.010976  ...  0.539758  0.152914  0.122563 -0.189758   

       f_96      f_97      f_98      f_99      target  kfold  
0 -1.483595 -1.962491  0.009401 -0.603869  -60.918021      1  
1 -0.685433 -0.243252 -0.249976 -0.469559  141.110046      1  
2 -1.105466  0.557212  0.565329  1.421766  364.577941      3  
3  2.595066  1.421216 -0.314818 -0.806506 -198.441232      3  
4 -0.879580  0.935963  0.225654 -1.581781   72.961683      1  

[5 rows x 103 columns]